### ISSUE TITLE
Empty edit fields without content are not being announced

### ISSUE THREAD

**Issue by PatrykMis** [Irineu333/SpeakTouch#109]
## Describe the bug:

Empty edit fields without label and description are not being announced

## To Reproduce:

Open some app with edit fields which are empty, without any description nor label and try to focus them either by touch exploration or gestures. One example app is Pyszne.pl while adding address fields before checkout

## Expected behavior

They should be focusable and being announced, even if the one possible thing to announce is only "edit field".

## More infos:
App version: 1.0.0-DEV
Android version: 13, 14
Device: Google Pixel 4, Google Pixel 8

**Comment by Irineu333** [comment]
Congratulations on the find.

**Comment by Irineu333** [comment]
Do you have several cell phones? Just to test on different devices?

**Comment by Irineu333** [comment]
This happens because the app does not focus on nodes without content. To correct this, just consider any edit field inherently readable, in `NodeValidator.hasContentToRead`, just as we do with any checkable node

**Comment by PatrykMis** [comment]
> Do you have several cell phones? Just to test on different devices?

I have even one more phone to test, three in total.

**Comment by Irineu333** [comment]
This is very impressive. Accessibility through the emulator is bad, right?
