### ISSUE TITLE
App is not reading state from custom checkable

### ISSUE THREAD

**Issue by Irineu333** [Irineu333/SpeakTouch#111]
## Describe the bug:

If you create a custom view with the properties of a checkable, even if you define `isCheckable`, Speak Touch will not read its state.

## To Reproduce:

In the **test** module, there is an example of `CustomCheckable`.

## Expected behavior

It should read the state: **selected** or **not selected**. Just like the **talkback**.

## Screenshots:

Talkback

https://github.com/NeoA11y/SpeakTouch/assets/45833588/f8422f4f-49fa-46ac-963b-12b310283a5c

Speak Touch

https://github.com/NeoA11y/SpeakTouch/assets/45833588/579a37df-2ae8-4eac-8fbd-87fa9edd481b

## More infos:
App version: 1.0.0-DEV
Android version: Android 12
Device: Moto G30

**Comment by PatrykMis** [comment]
It depends on the branch selected. In general, on branch where refactoring Reader class has begun, the behavior is similar to TalkBack: it reads the switch only, not label itself; though it's rather clear when switch is next to label by either exploration or left-to-right gesture.

**Comment by Irineu333** [comment]
@PatrykMis I didn't understand.

**Comment by PatrykMis** [comment]
It's an issue already linked to working and approved pull request. I didn't notice, sorry.
