### ISSUE TITLE
Checkables always reading as checked

### ISSUE THREAD

**Issue by Irineu333** [Irineu333/SpeakTouch#91]
## Describe the bug:

The app is reading all checkables as activated.

**Comment by PatrykMis** [comment]
Switches? I think rather radio buttons.

**Comment by Irineu333** [comment]
I don't think it's exclusive to radio buttons, switches or checkboxes. I think the problem is the checkables in general, right?

**Comment by Irineu333** [comment]
I need to improve the Reader class.

**Comment by Irineu333** [comment]
In the Reader class, look for the getCheckable function. You will understand why this bug 😂

**Comment by PatrykMis** [comment]
Ah yes I see 😂

Even I would fix this but what if checkable elements should have "checked" or "unchecked"/"not checked" string while switches should have "enabled"/"disabled" string?

**Comment by Irineu333** [comment]
It makes sense! It's time to improve this class. I'll create an issue for this [^1].

[^1]: #97

**Comment by Irineu333** [comment]
If you want to correct it, feel free.

**Comment by PatrykMis** [comment]
And similarly toggle buttons should have "pressed"/"not pressed".
